import dotenv from 'dotenv';
dotenv.config();
export const {
    PORT,  SECRET_KEY, DEV_DB_URL, SITE_URL, MODE, LOCAL_DB_URL, TEST_DB_URL,PROD_DB_URL, CLOUDINARY_FOLDER, 
    CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,
    FACEBOOK_APP_ID,FACEBOOK_APP_SECRET,TWITTER_CONSUMER_KEY,
    TWITTER_CONSUMER_SECRET,MAIL_SERVICE, MAIL_SENDER, MAIL_PASS, MAIL_USER, TENANT_DATABASE_POOL,
    SENDGRID_USERNAME, SENDGRID_PASSWORD, SENDGRID_API_KEY } = process.env;